# Generated by Django 2.2.25 on 2022-01-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0002_auto_20220116_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
